# This file contains the information needed for Shopify to authenticate
# requests and edit/update your remote theme files.
# DOCUMENTATION LINKS:
# --------------------
#   Config Variables | http://shopify.github.io/themekit/configuration
#   Ignore Patterns  | http://shopify.github.io/themekit/ignores

development:
  password: ${SHOPIFY_PASSWORD}
  theme_id: "${DEVELOPMENT_THEME}"
  store: ${STORE_URL}
  ignore_files:
    - README.md
    - .gitignore
    - config/settings_data.json
    - assets/bundle.js.map
    - locales/
    - "*.png"
    - "*.jpg"  
    - "*.jpeg" 
    - "*.svg" 
    - "*.gif" 
    - "*.mp4"
    - "*.JPG"
    - "*eot"
    - "*woff"
    - "*ttf"
    - "*.js.map"
    - "templates/*.json"

production:
  password: ${SHOPIFY_PASSWORD}
  theme_id: "${PRODUCTION_THEME}"
  store: ${STORE_URL}
  ignore_files:
    - README.md
    - .gitignore
    - config/settings_data.json
    - assets/bundle.js.map
    - locales/
    - "*.png"
    - "*.jpg"  
    - "*.jpeg" 
    - "*.svg" 
    - "*.gif" 
    - "*.mp4"
    - "*.JPG"
    - "*eot"
    - "*woff"
    - "*ttf"
    - "*.js.map"
    - "templates/*.json"
